build_validation_report <- function(cfg,inventory,rho_tab,primary,boundary,multiplicity,trajectory,spatial,ctx,simulation_files=character()){
  path<-file.path(ctx$root,"validation","validation_report.md");ensure_dir(dirname(path));s<-primary$summary
  lines<-c("# v5.6 validation report","",paste0("- Run ID: `",ctx$run_id,"`"),paste0("- Config hash: `",ctx$config_hash,"`"),paste0("- Code hash: `",ctx$code_hash,"`"),paste0("- Input fingerprint: `",inventory$fingerprint,"`"),paste0("- Primary scenario: `",primary$id,"`"),paste0("- Monte Carlo rule: `",cfg$supf$p_rule,"`; B = ",supf_mc_B_description(cfg)),paste0("- Primary FDR: ",cfg$multiple_testing$primary_method," at alpha = ",cfg$multiple_testing$alpha),"","## Response-specific rho","",paste(capture.output(print(rho_tab[,intersect(c("response","residual_model","residual_rho_raw_median","bias_corrected_rho","correction_hit_bound"),names(rho_tab))],row.names=FALSE)),collapse="\n"),"","## Primary summary","",paste(capture.output(print(s,row.names=FALSE)),collapse="\n"),"","## Automated QA flags","")
  flags<-character()
  if(any(rho_tab$correction_hit_bound %||% FALSE,na.rm=TRUE))flags<-c(flags,"- WARNING: at least one corrected rho hit the configured bound.")
  if(any(s$min_rank_at_mc_floor>1,na.rm=TRUE))flags<-c(flags,paste0("- INFO: finite-MC p-value resolution implies the smallest possible p-value can enter FDR only at rank >= ",paste(paste0(s$response,":",s$min_rank_at_mc_floor),collapse=", "),"."))
  if(!is.null(trajectory)&&nrow(trajectory$summary)&&any(trajectory$summary$coverage_warning,na.rm=TRUE))flags<-c(flags,"- WARNING: at least one regional trajectory has materially varying valid raster area across years.")
  if(!length(flags))flags<-"- No configured automatic warning threshold was triggered."
  lines<-c(lines,flags,"","## Interpretation constraints","","- Pixel bootstrap frequencies are conditional stability frequencies for primary selected recovery pixels, using the frozen primary whole-map FDR p-value cutoff; they are not posterior probabilities.","- Regional trajectory p-values are secondary pointwise Monte Carlo results, not part of the raster FDR family.","- Adjusted IoU uses an independence/prevalence reference and is descriptive, not a spatial-autocorrelation-aware null test.","- The equal-candidate-year ratio is a descriptive uniform reference, not a boundary-bias-corrected p-value.","- Missing-year-pattern-specific SupF calibration is not implemented; inferential raster cells must have complete annual series.")
  if(length(simulation_files))lines<-c(lines,"","## Simulation outputs","",paste0("- `",basename(simulation_files),"`"))
  writeLines(lines,path,useBytes=TRUE);invisible(path)
}
